# Generated by Django 4.1.6 on 2023-02-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gametype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Games', to='levelupapi.game_type'),
        ),
    ]
